// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrbbkiaguqmcgwvibiqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyYmJraWFndXFtY2d3dmliaXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDY2OTgsImV4cCI6MjA2ODY4MjY5OH0.RGb7hm46SS22em84PNgJD0P9jSVzbyhpoxue6E3rN6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});